In [9]:
'''np.array'''

import numpy as np

a = np.array([1,2,3,3,4]) #It is 1D array we call it vector'

print(a)
print(type(a))

[1 2 3 3 4]
<class 'numpy.ndarray'>


In [12]:
b = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(b) #2D arrays are usually called matrix

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [15]:
c = np.array([[[2,2],[2,2],[2,3],[4,5]]])
print(c) #3D arrays are called tensor

[[[2 2]
  [2 2]
  [2 3]
  [4 5]]]


In [17]:
#dtype
np.array([2.3,3.4], dtype = bool)

array([ True,  True])

In [24]:
#arange
np.arange(1,11,2)
np.arange(1,21).reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [30]:
#np.ones and np.zeros (they just exist to intialize arrays)
np.ones([3,2])


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [38]:
np.random.random((2,3)) #the random generated values will be between 0 and 1

array([[0.67550304, 0.33582301, 0.92861787],
       [0.05511474, 0.54304469, 0.58236262]])

In [41]:
#np.linspace (every two numbers in the given range will be equally spaced)
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [42]:
#np.identity (creates the identity matrix, diagonal items will be 1)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
a1 = np.arange(10)
print(a1)
a2 = np.arange(12, dtype = float).reshape(3,4)
print(a2)
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [53]:
#ndim (tells the dimension of array)
a1.ndim
a2.ndim
a3.ndim

3

In [55]:
#shape (how many items exists in each direction)
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
#size (total number of items)
a3.size #2x2x2

8

In [65]:
a1 = np.arange(12).reshape(3,4)
print(a1)
a2 = np.arange(12,24).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [69]:
#scalar operations
#airthmatic operations (sare aithmatic operations work krege)

a1 * 2
a1 + 2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [70]:
#Relational (har item se jake compare kro and return bool)
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
#vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [77]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print()
print(a1)

[[0.25227645 0.83212565 0.14663364]
 [0.49637826 0.79845963 0.15077397]
 [0.7857497  0.2650486  0.03214641]]

[[25. 83. 15.]
 [50. 80. 15.]
 [79. 27.  3.]]


In [80]:
#max/min/sum/prod (sum and prod will be the sum and prod of each single element)

np.prod(a1) 

11950132500000.0

In [83]:
#max/min/sum/prod
# 0 -> col and 1 -> row

np.max(a1,axis = 0)

array([79., 83., 15.])

In [85]:
#Dot product
# (2,3) * (3,2)  ,,1s col == 2nd row for prod to happen

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2 , a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [86]:
# log and exp

np.exp(a1)

array([[7.20048993e+10, 1.11286375e+36, 3.26901737e+06],
       [5.18470553e+21, 5.54062238e+34, 3.26901737e+06],
       [2.03828107e+34, 5.32048241e+11, 2.00855369e+01]])

In [91]:
#round/floor/ceil
# round -simple round off
# floor -piche wle integer ki taraf fekta hai
# ceil -agey wle integer ki taraf fekta hai

np.ceil(np.random.random((2,3))*100)

array([[48., 91.,  7.],
       [82.,  6., 72.]])

In [95]:
# INDEXING AND SLICING

a1 = np.arange(12)
print(a1)
print()

a2 = np.arange(12).reshape((3,4))
print(a2)
print()

a3 = np.arange(8).reshape((2,2,2))
print(a3)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [98]:
a1[-1]
a2[1,3]
a3[0,1,1]

3

In [122]:
a1[ -1]

11

In [125]:
a2[0:2, 1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [126]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [129]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [146]:
a3[0::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [148]:
#Iterating

print(a1)

for i in a1:
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [150]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [151]:
#There is this method in numpy library to print each element of an array of any dimention, works even for 100D

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# Reshaping 
# we have 3 methods of reshaping
# 1) reshape (we already know)
# 2) transpose row ka col and col ka row
# 3) ravel (kitne bhi dimension ki array ko 1D bna dega)

In [155]:
# transpose
print(a2)
np.transpose(a2)
a2.T #easy syntax

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [161]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [166]:
#Stacking
''' 1) Horizontal Stackig
    2) Vertical stacking'''

a4 = np.arange(12).reshape(3,4)
print(a4)
print()
a5 = np.arange(12,24).reshape(3,4)
print(a5)
print()

#horizontal stacking
np.hstack((a4,a5,a5,a4))

#verticla stacking
np.vstack((a4, a5))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [171]:
#Splitting
''' 1) Horizontal Splitting
    2) Vertical splitting'''

#1 jaise stack kra waise hi hta do, hsplit
print
np.hsplit(a4,2)

#2 vsplit
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]